#ifndef _MATERIAL_DEF_H_
#define _MATERIAL_DEF_H_

enum class MATERIAL_TYPE
{
    M_NULL,
    M_RED,
    M_YELLOW,
    M_AQUA,
    M_PURPLE,
    M_GREEN,
    M_BLUE,
    M_WHITE,

    M_LENA,
    M_CHESSBOARD,

    M_MIRROR,
    M_GLASS,

    M_DIELECTRIC,
    M_COMBINED,

    M_CONDUCTOR,

    M_MEASURED_WHITE_BRDF,
    M_MEASURED_GREEN_BRDF,
    M_MEASURED_METAL_BRDF,
    M_MEASURED_MINT_BRDF,
    M_MEASURED_SARI_SILK_BRDF,
    M_MEASURED_BRUSHED_ALUMINIUM_BRDF,
    M_MEASURED_GREEN_PVC_BRDF,
    M_MEASURED_TARKIN_TUNIC_BRDF,
};

#endif